spring.application.name=redirection-service


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Babla@123
spring.datasource.url=jdbc:postgresql://localhost:5432/url_db
spring.jpa.hibernate.ddl-auto=update

server.port=8082

#redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.ssl.enabled=false
cache.key.ttl=30

#spring.kafka.bootstrap-servers=localhost:9092
#
## Producer config
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
##spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#
## Optional: for sending JSON objects
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#spring.kafka.producer.retries=3
#spring.kafka.producer.properties.retry.backoff.ms=2000
#spring.kafka.producer.properties.retry.backoff.max.ms=8000
#
## Idempotency
#spring.kafka.producer.enable-idempotence=true



# Kafka
kafka.bootstrap-servers=localhost:9092

# Producer
kafka.producer.retries=3
kafka.producer.retry-backoff-ms=2000
kafka.producer.retry-backoff-max-ms=8000
kafka.producer.enable-idempotence=true


