apiVersion: v1
kind: ConfigMap

metadata:
  name: kafka-config
  namespace: tiny-url

data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_LISTENERS: "PLAINTEXT://:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-0.kafka:9092"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_LOG_RETENTION_HOURS: "168"