apiVersion: v1
kind: ConfigMap

metadata:
  name: analytics-service-config
  namespace: tiny-url

data:
  SPRING_APPLICATION_NAME: analytics-service

  # Database
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/analytic_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  KAFKA_CONSUMER_GROUP_ID: click-event-group
  KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
  KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: "false"

  KAFKA_CONSUMER_MAX_POLL_RECORDS: "100"
  KAFKA_CONSUMER_FETCH_MIN_BYTES: "1"
  KAFKA_CONSUMER_FETCH_MAX_WAIT_MS: "5000"