apiVersion: apps/v1
kind: Deployment

metadata:
  name: redirection-service
  namespace: tiny-url

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redirection-service

  template:
    metadata:
      labels:
        app: redirection-service

    spec:
      containers:
        - name: redirection-service
          image: redirection-service:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8082

          envFrom:
            - configMapRef:
                name: redirection-service-config

            - secretRef:
                name: redirection-service-secret