apiVersion: v1
kind: ConfigMap

metadata:
  name: url-service
  namespace: tiny-url

data:
  SPRING_APPLICATION_NAME: url-service

  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_db
  SPRING_DATASOURCE_USERNAME: postgres

  SPRING_JPA_HIBERNATE_DDL_AUTO: update

  SERVER_PORT: "8081"
  SERVER_SERVLET_CONTEXT_PATH: /api/v1

  APP_URL_REDIRECTION_SERVICE_URL: /
  APP_URL_DEFAULT_EXPIRATION_DAYS: "30"