spring.application.name=url-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Babla@123
spring.datasource.url=jdbc:postgresql://localhost:5432/url_db
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/api/v1
server.port=8081

app.url.redirection-service-url=http://localhost:8082/
app.url.default-expiration-days=30

