spring.application.name=analytics-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Babla@123
spring.datasource.url=jdbc:postgresql://localhost:5432/analytic_db
spring.jpa.hibernate.ddl-auto=update

# Consumer
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=click-event-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.enable-auto-commit=false
#spring.kafka.listener.ack-mode=BATCH
#
#spring.kafka.consumer.properties.spring.json.use.type.headers=false
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

kafka.bootstrap-servers=localhost:9092
kafka.consumer.group-id=click-event-group
kafka.consumer.auto-offset-reset=earliest
kafka.consumer.enable-auto-commit=false

kafka.consumer.max-poll-records=100
kafka.consumer.fetch-min-bytes=1
kafka.consumer.fetch-max-wait-ms=5000